### ISSUE TITLE
Error finding/creating FileData

### ISSUE THREAD

**Issue by hellricer** [RapidEdwin08/imp#3]
After installing imp, I'm getting these errors in the logs.

```
May 28 17:36:47 lvl0:   Error finding/creating FileData for "/home/pi/RetroPie/retropiemenu/imp/music/bgm/A-SIDE", skipping.
May 28 17:36:47 lvl0:   Error finding/creating FileData for "/home/pi/RetroPie/retropiemenu/imp/music/bgm/B-SIDE", skipping.
```

I would happily ignore them, but they show up when I run games and it looks ugly... Any idea what could it be caused by?

**Comment by RapidEdwin08** [comment]
Those Errors are indicating the BGM Folders do not exist.
IMP checks for the presence of these directories and attempts to create them if not found.
If you are using a User Name 0ther than Pi, 2022.10 has changes made to accommodate when a $HOME folder is something 0ther than /home/pi.
Can you confirm if this issue still occurs on 2022.10?

**Comment by RapidEdwin08** [comment]
Confirmed this is no longer an issue on [v2023.01].
