### ISSUE TITLE
Auto play music at ROMs closed

### ISSUE THREAD

**Issue by gloony** [RapidEdwin08/imp#5]
When you disable the music start at boot, the music is launched when a game is closed.
Any way to disable it and be started only manually ?

**Comment by RapidEdwin08** [comment]
Thanks for Reporting this.
Issue found, should be fixed now.
https://github.com/RapidEdwin08/imp/commit/3c7eda311493f1659982b457026bd468abbd1aea

**Comment by gloony** [comment]
Great, thank you for your support !
I miss the notification before, but I just made the test now and it work like a charm !
